### ISSUE TITLE
Optimize the pathfinding code

### ISSUE THREAD

**Issue by T-Rizzle12** [T-Rizzle12/Custom-Gmod-Bot#10]
Currently, Pathfinding is very expensive, “laggy,” when pathing to a player far away from them. It will also severely lag the game if the bot can’t path to the player at all. I have partially fixed this issue by creating a secondary pathfinding system when the player is far away, but the main can and will lag the game. What could be causing the lag?
# Todo:
- [x] Find the cause of the lag
- [x] Attempt to fix the cause of the lag

**Comment by strubium** [comment]
This might not be a bug with your project, it could be gmod navmeshes being huge and unoptimized. Maybe try generating a new one with [Navmesh Optimizer](https://steamcommunity.com/sharedfiles/filedetails/?id=2878197619   )

**Comment by strubium** [comment]
How does this program define "nodes"? Are these just normal ai nodes or custom navmesh thingamabobbers.

**Comment by T-Rizzle12** [comment]
Nodes are nav areas. 
The list is used to check what nodes have already been checked.
The Open list is the list of nodes that need to be checked.
The Closed list is the list of nodes that have already been checked.

**Comment by strubium** [comment]
Hmmm, Ok so does the bot need to keep all of the checked areas? Could it start deleting old ones after it checks 300 or so?

**Comment by T-Rizzle12** [comment]
The bot needs all of the checked areas. This prevents the bot from checking nodes it has already checked.

**Comment by T-Rizzle12** [comment]
After some testing sorting is not the reason for the lag.
I wonder what could be the cause of the lag.

**Comment by strubium** [comment]
> I wonder if I should use multiple tables instead of one main table for pathfinding. -T-Rizzle12

That would probably work, idk at this point.

**Comment by strubium** [comment]
> The bot needs all of the checked areas. This prevents the bot from checking nodes it has already checked.

Yes, but what happens if the player moves into a checked area while the bot is looking for the player? Will the bot just get confused?  And, combining nav areas would lower the amount it has to keep track of, which might still help.

**Comment by T-Rizzle12** [comment]
> > The bot needs all of the checked areas. This prevents the bot from checking nodes it has already checked.
> 
> Yes, but what happens if the player moves into a checked area while the bot is looking for the player? Will the bot just get confused? And, combining nav areas would lower the amount it has to keep track of, which might still help.

The lists get emptied every pathfind and it paths to the player’s position, not the player itself. So that should never happen.

Yes, combining nav areas would make it better, but not everyone does that and I need to make this addon as user friendly as possible. I also noticed that pathfinding will lag even if their is a possible path if it’s longer than 30-50 areas.

**Comment by strubium** [comment]
Yeah, that makes sense. Sorry. 

Honesty, this has come to the extent of my knowledge. You said that it uses a cheaper version of pathfinding when the bot is far away, what's the difference between both versions?

**Comment by T-Rizzle12** [comment]
> > > Yeah, that makes sense. Sorry.
> > > Honesty, this has come to the extent of my knowledge. You said that it uses a cheaper version of pathfinding when the bot is far away, what's the difference between both versions?
> > 
> > 
> > The main version uses custom methods that can detect ladders. The cheaper version uses valve’s pathfinding methods, but they cannot detect ladders.
> 
> Ah, alright. Possibly, you could program it to "discover" ladders when a new bot is created and only use the new pathfinding when the bot is close to a ladder.
> 
> Or, contact the guy who helped you with the original pathfinding and do a line-by-line comparison of all the differences between valve's pathfinding system and your pathfinding system.
> 
> Or or, change the code so that instead of 6000Hu before it uses the cheaper version, is 3000, or some other smaller number

@strubium Using CS:GO Source Code, I managed to recreate PathFollower. Its a a lot cheaper than my current version and it can even detect ladders. Their is currently one bug. Properly creating the path, "The bot loves to skip ladder nodes"

**Comment by T-Rizzle12** [comment]
After some more testing it can now properly detect and use ladders. I will keep the old system mostly because it makes nicer looking paths, but the newer system is cheaper and almost just as efficent. :)

**Comment by strubium** [comment]
> After some more testing it can now properly detect and use ladders. I will keep the old system mostly because it makes nicer looking paths, but the newer system is cheaper and almost just as efficient. :)

Hell yeah, brother! That's how its done!
