### ISSUE TITLE
Bot Vision Interface

### ISSUE THREAD

**Issue by T-Rizzle12** [T-Rizzle12/Custom-Gmod-Bot#21]
For the Vision interface, it will check if the enemy is visible and in the bot's FOV. The bot’s LOS will be effected by the light level of an area, “the bot will need to turn it’s flashlight on in order to partially negate the distance penalty. If possible I will try to make the bot also be effected by fog.

Todo:
- [x] Create a basic LOS check
- [x] Add a function so the bot can be temporarily blind, “basically support for flash bangs.”
- [x] Add detection for fog

I will not Add detection for light levels until I can find an efficient way to compute light levels around entities.

**Comment by strubium** [comment]
If you want to have the bots sight affected by fog, you can try finding a way to read the value of [env_fog_controller](https://developer.valvesoftware.com/wiki/Env_fog_controller) the doing some "sweet gamer math" to change the bots visibility cone

**Comment by T-Rizzle12** [comment]
> If you want to have the bots sight affected by fog, you can try finding a way to read the value of [env_fog_controller](https://developer.valvesoftware.com/wiki/Env_fog_controller) the doing some "sweet gamer math" to change the bots visibility cone

Interesting, I will look into this. I will work on fog and light level checks after I get the basic implementation of LOS working.

**Comment by T-Rizzle12** [comment]
> > If you want to have the bots sight affected by fog, you can try finding a way to read the value of [env_fog_controller](https://developer.valvesoftware.com/wiki/Env_fog_controller) the doing some "sweet gamer math" to change the bots visibility cone
> 
> Interesting, I will look into this. I will work on fog and light level checks after I get the basic implementation of LOS working.

It looks like there are some functions in the Gmod api regarding fog. Sadly it is client side only. This means I will have to send a net message to a real player, compute everything on their computer and resend the data back to the server. 
This is going to take longer than I expected, ( I knew making fog detection was going to be hard, but this require optimization, especially on the net messages )

**Comment by strubium** [comment]
> 

Oof, that sucks. Don't bother with this now, seems like a pain in the ass for very little. 

How does the bot know when to turn on its flashlight?

**Comment by strubium** [comment]
> > Oof, that sucks. Don't bother with this now, seems like a pain in the ass for very little.
> > How does the bot know when to turn on its flashlight?
> 
> I grab the light level around the bot. Sadly this is a client side function, so I had to use net messages. This is how I grab the light level. First I set a next message to a random human player, compute the light level on their computer, and finally send the data back to the server. It’s not very expensive and works perfectly.

Oh! Ok, I've submitted a feature request to Facepunch to make it work on both client and server [here](https://github.com/Facepunch/garrysmod-requests/issues/2071) although I don't think anything will come out of it, and like you said, it works perfectly. 

I assumed you were talking about [render.GetFogDistances](https://wiki.facepunch.com/gmod/render.GetFogDistances) that is only client-side if you were to use it, perhaps the bot definitely shouldn't see anything past the fog end distance.

**Comment by T-Rizzle12** [comment]
> > > Oof, that sucks. Don't bother with this now, seems like a pain in the ass for very little.
> > > How does the bot know when to turn on its flashlight?
> > 
> > 
> > I grab the light level around the bot. Sadly this is a client side function, so I had to use net messages. This is how I grab the light level. First I set a next message to a random human player, compute the light level on their computer, and finally send the data back to the server. It’s not very expensive and works perfectly.
> 
> Oh! Ok, I've submitted a feature request to Facepunch to make it work on both client and server [here](https://github.com/Facepunch/garrysmod-requests/issues/2071) although I don't think anything will come out of it, and like you said, it works perfectly.
> 
> I assumed you were talking about [render.GetFogDistances](https://wiki.facepunch.com/gmod/render.GetFogDistances) that is only client-side if you were to use it, perhaps the bot definitely shouldn't see anything past the fog end distance.

Yep, I’m sure I will figure out something.

**Comment by T-Rizzle12** [comment]
Found this in CS:GO Source code
//-----------------------------------------------------------------------------
// Purpose: return 0-1 ratio where zero is not obscured, and 1 is completely obscured
//-----------------------------------------------------------------------------
float CBaseCombatCharacter::GetFogObscuredRatio( float range ) const
{
	fogparams_t fog;
	GetFogParams( &fog );

	if ( !fog.enable )
		return 0.0f;

	if ( range <= fog.start )
		return 0.0f;

	if ( range >= fog.end )
		return 1.0f;

	float ratio = (range - fog.start) / (fog.end - fog.start);
	ratio = Min( ratio, fog.maxdensity.Get() );
	return ratio;
}

**Comment by T-Rizzle12** [comment]
Also found this in CS:GO source code
//-----------------------------------------------------------------------------
// Purpose: return true if given target cant be seen because of fog
//-----------------------------------------------------------------------------
bool CBaseCombatCharacter::IsHiddenByFog( float range ) const
{
	if ( GetFogObscuredRatio( range ) >= 1.0f )
		return true;

	return false;
}

**Comment by T-Rizzle12** [comment]
I have an idea on how to compute the fog. Since the fog has some cheap functions in the client. I will grab the fog information from a player an relay it back to the server. Allowing me to compute everything on the server.

**Comment by T-Rizzle12** [comment]
> I have an idea on how to compute the fog. Since the fog has some cheap functions in the client. I will grab the fog information from a player an relay it back to the server. Allowing me to compute everything on the server. I can also compute the fog data every few seconds making this very optimized.
> 
> Edit - Added more information

After some attempts, I think I will try to grab the information from the env_fog_controller. Since I might be able to compute everything on the server. Saving not only sending net messages, but computer resources.

**Comment by T-Rizzle12** [comment]
I just noticed something, when checking the light level I should check it around the entity the bot is looking at. This is a lot harder than I thought since the function to check light level is client side. I can use Network Vars and every few seconds or something and compute the light levels on a player’s computer, but how can I keep the code from lagging the player.
