### ISSUE TITLE
Bot Memory Interface

### ISSUE THREAD

**Issue by T-Rizzle12** [T-Rizzle12/Custom-Gmod-Bot#23]
For the Memory Interface, this is where the bot will keep track of enemies it has seen before and check if they are still visible, “it will use the old visibility checks when checking LOS.”

Todo:
- [x] Create a table to store list of known enemies
- [x] Check each enemy on the list and check if they are alive, valid, and visible
- [x] Make enemies currently in the bot's LOS have a higher priority over enemies in the known enemy list, unless an enemy on the know enemy list is closer.
- [x] Upon taking damage from an enemy add them to the known enemy list

**Comment by strubium** [comment]
How does a large number of enemies affect this system? I usually play against a crap ton of left 4 dead zombies, will this cause lag?

**Comment by T-Rizzle12** [comment]
> How does a large number of enemies affect this system? I usually play against a crap ton of left 4 dead zombies, will this cause lag?

So far a few tests with 3 bots with 30 enemies in all 3 bot’s known enemy list has little to no lag. It’s very optimized.

**Comment by strubium** [comment]
Wow! That is really optimized!
