### ISSUE TITLE
Does the bot require a "owner?"

### ISSUE THREAD

**Issue by strubium** [T-Rizzle12/Custom-Gmod-Bot#25]
I know it does at the moment, but would it be possible to create a bot that's "free" and roams around the map at its own willpower?

You don't need to focus on this now, or even do it, but here is my brainstorming code.
<code>NewBot.IsTRizzleBot			=	args[ 16 ] or true</code> (Not sure I modified this right)
<code>NewBot.Owner				=	args[ 16 ] or ply </code>   

Argument 16 would not be required when the bots are created, and only server admins could edit the bot after it's created. The bot would "follow" anything but could just be programed to go to random points.

**Comment by T-Rizzle12** [comment]
> I know it does at the moment, but would it be possible to create a bot that's "free" and roams around the map at its own willpower?
> 
> You don't need to focus on this now, or even do it, but here is my brainstorming code. `NewBot.IsTRizzleBot = args[ 16 ] or true` (Not sure I modified this right) `NewBot.Owner = args[ 16 ] or ply `
> 
> Argument 16 would not be required when the bots are created, and only server admins could edit the bot after it's created. The bot would "follow" anything but could just be programed to go to random points.

IMPORTANT: Never set IsTRizzleBot to anything other than true!!!
IsTRizzleBot is used to check if this is a bot that should be controlled by my addon. If you change this to anything else, the bot will do absolutely nothing, “unless you have another addon that controls all bots in general.”

As for the bot Owner, currently the bot will fail to work without one as most functions require it. I have considered bots without an owner, but I don’t see a point for the bot not to have an owner in the first place. Even then it would take a decent amount of time for me to program a decent AI that can make its own decisions.

Note - I’m not saying this is a horrible suggestion, just not in the scope of this addon. I have planned to make tactical combat AI as well as making a way to command the bot.

**Comment by strubium** [comment]
Figured, mostly just asking if a modified "base" of this addon would work. Although not that I'm gonna make my own, ill be way over my head. Thank you again!

**Comment by T-Rizzle12** [comment]
@strubium
When I release #30, the bot will no longer require a owner to function as I have added some fail safes and changed the scope of this addon. This addon will now be a bot base for me to use to make versions of the bot to play other game modes.

**Comment by strubium** [comment]
> @strubium
> When I release #30, the bot will no longer require a owner to function as I have added some fail safes and changed the scope of this addon. This addon will now be a bot base for me to use to make versions of the bot to play other game modes.

Wow! That's really cool! What happens when a bot is created without an owner?

**Comment by T-Rizzle12** [comment]
> > @strubium
> > When I release #30, the bot will no longer require a owner to function as I have added some fail safes and changed the scope of this addon. This addon will now be a bot base for me to use to make versions of the bot to play other game modes.
> 
> Wow! That's really cool! What happens when a bot is created without an owner?

For now the bot will pick a random sniper spot and hide there while looking for possible enemies. After a while the bot will pick another spot and do the same thing again. Its not much for now, but I gives me the base I need when programing the bot for other game modes.
