### ISSUE TITLE
Why did I keep getting this error

### ISSUE THREAD

**Issue by Gvbavx** [T-Rizzle12/Custom-Gmod-Bot#45]
![20240125181535_1](https://github.com/T-Rizzle12/Custom-Gmod-Bot/assets/145967852/634310e5-c5b6-4339-b975-37f0a14d98fe)
![20240125181558_1](https://github.com/T-Rizzle12/Custom-Gmod-Bot/assets/145967852/879515de-1516-4633-b7b3-f461688645fc)
![20240125182000_1](https://github.com/T-Rizzle12/Custom-Gmod-Bot/assets/145967852/c4829f99-3267-469b-a294-41345cc0114d)

And here is the video:https://www.youtube.com/watch?v=XVS2HlVDASo&ab_channel=Kiaggy

[Custom Gmod Bot] lua/autorun/server/trizzlebot_base.lua:5076: attempt to call method 'GetAimVector' (a nil value)
    1. IsThreatAimingTowardMe - lua/autorun/server/trizzlebot_base.lua:5076
        2. IsThreatFiringAtMe - lua/autorun/server/trizzlebot_base.lua:5090
            3. IsImmediateThreat - lua/autorun/server/trizzlebot_base.lua:5217
                4. SelectMoreDangerousThreat - lua/autorun/server/trizzlebot_base.lua:5272
                    5. GetPrimaryKnownThreat - lua/autorun/server/trizzlebot_base.lua:5156
                        6. fn - lua/autorun/server/trizzlebot_base.lua:3403
                            7. unknown - lua/ulib/shared/hook.lua:109

The addons I used

![20240125182435_1](https://github.com/T-Rizzle12/Custom-Gmod-Bot/assets/145967852/5ebb7181-f302-42aa-9f51-49b977ad402e)

![20240125182438_1](https://github.com/T-Rizzle12/Custom-Gmod-Bot/assets/145967852/d985ff5b-675b-49dc-a4ea-cb0aab820de6)

It's obvious this has to do with the npcs. But why?

**Comment by T-Rizzle12** [comment]
It a bug regarding the bots checking if an enemy is firing a weapon at them. This shouldn’t be too hard to fix!

**Comment by T-Rizzle12** [comment]
Ok, I found the cause of the bug. Apparently, it's trying to call a function that doesn't exist on NextBots. It shouldn't take me too long to fix.
