### ISSUE TITLE
Bots appear to shoot into the sky when attacking in some places?

### ISSUE THREAD

**Issue by Gvbavx** [T-Rizzle12/Custom-Gmod-Bot#49]
https://github.com/T-Rizzle12/Custom-Gmod-Bot/assets/145967852/9c5f9d05-883f-48ba-8ef6-d30f0a1d8250

https://github.com/T-Rizzle12/Custom-Gmod-Bot/assets/145967852/0f1ec7c2-1a9f-4188-b1a2-4266953dd64b

https://github.com/T-Rizzle12/Custom-Gmod-Bot/assets/145967852/cece87b4-c52e-4497-90a7-81cd084fa1d0

This only happened in some places of the maps, I don't know why because there is nothing in the sky? I don't see this happen in other maps so far?
Maps I played:Another Universe (Part 4) and Another Universe (Part 8)
Addons used:Only Custom Gmod Bot

**Comment by T-Rizzle12** [comment]
It looks like the issue is created by an entity labeled npc_enemyfinder. Thankfully, the source SDK forces the npc_enenmyfinder to have the no-draw flag. I should have made the bot ignore entities with no-draw set so I will include a fix in the next update.

**Comment by T-Rizzle12** [comment]
@Gvbavx 
Just want to check, did the recent update resolve this issue?

**Comment by Gvbavx** [comment]
> @Gvbavx Just want to check, did the recent update resolve this issue?

Yes, they don't attack entities with the nodraw flag set anymore
