### ISSUE TITLE
Bot chat command bug?

### ISSUE THREAD

**Issue by Gvbavx** [T-Rizzle12/Custom-Gmod-Bot#67]
![20241005220916_1](https://github.com/user-attachments/assets/3bc63e04-c316-4d63-88ec-35667c81f405)
![20241005220930_1](https://github.com/user-attachments/assets/f60d57ee-e653-4e74-9347-4b146ee988cc)
![20241005220933_1](https://github.com/user-attachments/assets/f5ad20c0-05ba-4331-9c56-021a86cab4c0)
I named these two bots Gordon and Gordon2, I told Gordon2 to hold the position but Gordon was responding to the chat command too!

**Comment by T-Rizzle12** [comment]
The issue lies with how the bot checks the name the player said in the chat.......the only way I could fix this is if I change how the bot checks the player's name internally.......

**Comment by T-Rizzle12** [comment]
I just checked and its an issue with https://wiki.facepunch.com/gmod/string.find, I would have to find a workaround.....

**Comment by T-Rizzle12** [comment]
I have been doing a lot of experimenting with the string manipulation functions.
Here is some experimental code I intend to test that if it works, it will fix the issue entirely.
```
local botNamePattern = string.format( "^(%s) +(.*)$", me:Nick() )
local textTable
local _, command = string.match( text, botNamePattern )

if isstring( command ) then -- Only run the command if the bot name was said first!

	textTable = string.Explode( " ", command ) -- Grab everything else after the name!
	command = textTable[ 1 ] and textTable[ 1 ]:lower() -- Make it case insenstive

else

	local botsPattern = "^bots%s+(.*)$"
	local _, command2 = string.match( text:lower(), "bots" )
	if isstring( command2 ) then -- Check to see if the player is commanding every bot!

		textTable = string.Explode( " ", command2 ) -- Grab everything else after the name!
		command = textTable[ 1 ] and textTable[ 1 ]:lower() -- Make it case insenstive

	end

end
```

**Comment by T-Rizzle12** [comment]
Ok, just did the first test run and here are the results:
I have four bots:
Alyx Vance1
Alyx Vance2
Alyx1
Alyx2

The fix works as expected and the bot will only respond to its entire name!
However, the commanding all bots part of the command broke, but progress is progress!

**Comment by T-Rizzle12** [comment]
Alright, made some final changes and the issue appears to be fixed. I will create a bug-fix branch and add the updated files when I get the time to do so!
