### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by strubium** [T-Rizzle12/Custom-Gmod-Bot#8]
This looks really cool, but how do I install it?

**Comment by T-Rizzle12** [comment]
You download the latest release, "the file name is Custom.Gmod.Bot.zip."
Then you go to your Gary's mod directory and unzip the file in you addons folder
And that's it.

I'm working on putting this addon on the steam workshop because of how confusing it is to install the addon right now.

**Comment by strubium** [comment]
Thank you
